(function(){
'use strict';
const KEY='caetano_saas_v1';
const now=()=>new Date().toISOString();
const BRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const fmt=n=>BRL.format(Number(n||0));
const num=v=>{if(v===null||v===undefined||v==='')return 0;let s=String(v).trim(); if(/^\d+\.\d+$/.test(s))return Number(s); s=s.replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''); return Number(s)||0};
const uid=p=>(p||'id')+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const dateBR=d=>{if(!d)return''; const s=String(d).slice(0,10); if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[a,m,dd]=s.split('-');return `${dd}/${m}/${a}`} return s};
const today=()=>new Date().toISOString().slice(0,10);
const role=new URLSearchParams(location.search).get('role')||'jarvis';
const roleNames={superadmin:'Superadmin',jarvis:'Dono / Gerente',equipe:'Equipe / Açougueiro',cliente:'Cliente',clienteOficial:'Cliente Oficial'};
const modules=[
 ['dashboard','Dashboard','todos'],['pdv','PDV / Vendas','jarvis,equipe'],['pedidos','Encomendas','jarvis,equipe,cliente,clienteOficial'],['estoque','Estoque & Validade','jarvis,equipe'],['compras','Compras / NF-e','jarvis'],['clientes','Clientes / Fiado','jarvis'],['fornecedores','Fornecedores','jarvis'],['financeiro','Financeiro / DRE','jarvis'],['producao','Cortes & Produção','jarvis,equipe'],['notificacoes','Notificações','jarvis,equipe'],['ia','thIAguinho IA','superadmin,jarvis,equipe'],['modulos','Módulos por unidade','superadmin'],['auditoria','Auditoria','superadmin,jarvis']
];
const noMoneyRole=role==='equipe'||role==='cliente';
let DB=load();
let current='dashboard';
function blank(){return {tenant:{nome:'CAETANO Casa de Carnes',cnpj:'',telefone:'',endereco:'',modulos:{}},produtos:[],lotes:[],clientes:[],fornecedores:[],vendas:[],pedidos:[],compras:[],financeiro:[],producao:[],notificacoes:[],auditoria:[]}}
function load(){try{return Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return blank()}}
function save(){localStorage.setItem(KEY,JSON.stringify(DB));}
function audit(action,entity,id,before,after,motivo){DB.auditoria.unshift({id:uid('aud'),at:now(),role,usuario:localStorage.getItem('caetano_ultimo_login')||role,action,entity,id,before,after,motivo:motivo||''}); DB.auditoria=DB.auditoria.slice(0,1000); save();}
function notify(tipo,titulo,msg,perfil='jarvis',entidade={}){DB.notificacoes.unshift({id:uid('not'),at:now(),tipo,titulo,msg,perfil,lida:false,prioridade:tipo==='alerta'?'alta':'normal',entidade}); save();}
function isAllowed(id){const m=modules.find(x=>x[0]===id); if(!m)return true; if(m[2]==='todos')return true; if(!m[2].split(',').includes(role))return false; const cfg=DB.tenant.modulos||{}; return cfg[id]!==false;}
function nav(){const n=document.getElementById('nav'); n.innerHTML=''; modules.forEach(m=>{if(isAllowed(m[0])){const b=document.createElement('button'); b.className='nav-btn '+(current===m[0]?'active':''); b.textContent=m[1]; b.onclick=()=>go(m[0]); n.appendChild(b);}}); document.body.classList.toggle('no-money',noMoneyRole); document.getElementById('roleBadge').textContent=roleNames[role]||role; document.getElementById('tenantName').textContent=DB.tenant.nome||'CAETANO Casa de Carnes';}
function go(id){current=id; nav(); document.getElementById('title').textContent=(modules.find(m=>m[0]===id)||[,id])[1]; document.getElementById('crumb').textContent=roleNames[role]||role; render(); if(innerWidth<900)toggleMenu(false)}
function render(){({dashboard,pdv,pedidos,estoque,compras,clientes,fornecedores,financeiro,producao,notificacoes,ia,modulos,auditoria}[current]||dashboard)();}
function set(html){document.getElementById('view').innerHTML=html;}
function toast(msg){const t=document.createElement('div'); t.className='toast'; t.textContent=msg; document.getElementById('toast').appendChild(t); setTimeout(()=>t.remove(),3500)}
function toggleMenu(force){document.getElementById('side').classList.toggle('open',force===undefined?undefined:!!force)}
function toggleTheme(){const t=document.documentElement.dataset.theme==='dark'?'light':'dark'; document.documentElement.dataset.theme=t; localStorage.setItem('caetano_theme',t)}
function modal(title,body,foot=''){document.getElementById('modalTitle').textContent=title; document.getElementById('modalBody').innerHTML=body; document.getElementById('modalFoot').innerHTML=foot; document.getElementById('modal').classList.add('open')}
function closeModal(e){if(e===true||e.target?.id==='modal')document.getElementById('modal').classList.remove('open')}
function cepFill(cepId,prefix){const cep=document.getElementById(cepId).value.replace(/\D/g,''); if(cep.length!==8)return toast('CEP precisa ter 8 dígitos'); fetch('https://viacep.com.br/ws/'+cep+'/json/').then(r=>r.json()).then(d=>{if(d.erro)return toast('CEP não encontrado'); ['logradouro','bairro','localidade','uf'].forEach(k=>{const el=document.getElementById(prefix+k); if(el)el.value=d[k]||''})}).catch(()=>toast('Sem internet para buscar CEP. Preencha manualmente.'))}
function dashboard(){const venc=DB.lotes.filter(l=>l.validade&&days(l.validade)<=5).length; const aberto=DB.pedidos.filter(p=>!['entregue','cancelado'].includes(p.status)).length; const rec=DB.financeiro.filter(f=>f.tipo==='receber'&&f.status!=='pago').reduce((a,b)=>a+num(b.valor),0); const pag=DB.financeiro.filter(f=>f.tipo==='pagar'&&f.status!=='pago').reduce((a,b)=>a+num(b.valor),0); set(`<div class="grid cols-4"><div class="card kpi"><span>Pedidos abertos</span><strong>${aberto}</strong></div><div class="card kpi"><span>Lotes vencendo</span><strong class="${venc?'warn':''}">${venc}</strong></div><div class="card kpi"><span>A receber</span><strong class="money" data-money="1">${fmt(rec)}</strong></div><div class="card kpi"><span>A pagar</span><strong class="money" data-money="1">${fmt(pag)}</strong></div></div>${noMoneyRole?'<div class="card"><strong>Modo equipe:</strong> valores financeiros ficam ocultos por regra.</div>':''}<div class="grid cols-2"><div class="card">${statusPedidos()}</div><div class="card">${alertas()}</div></div>`)}
function statusPedidos(){return `<h3>Fluxo de encomendas</h3>${['novo','separando','pronto','entregue'].map(s=>`<p><span class="pill">${s}</span> ${DB.pedidos.filter(p=>p.status===s).length}</p>`).join('')}`}
function alertas(){const lots=DB.lotes.filter(l=>l.validade&&days(l.validade)<=5).slice(0,8); return `<h3>Alertas</h3>${lots.length?lots.map(l=>`<p class="warn">${esc(prodName(l.produtoId))} — lote ${esc(l.lote)} vence ${dateBR(l.validade)}</p>`).join(''):'<p class="subtle">Sem alertas críticos.</p>'}`}
function days(d){return Math.ceil((new Date(d+'T12:00:00')-new Date())/86400000)}
function prodName(id){return DB.produtos.find(p=>p.id===id)?.nome||'Produto'}
function pdv(){set(`<div class="toolbar"><button class="primary" onclick="App.openQuickSale()">Nova venda</button><button onclick="App.go('pedidos')">Encomendas</button></div>${table(['Data','Cliente','Itens','Total','Pagamento'],DB.vendas.map(v=>[dateBR(v.data),esc(findName(DB.clientes,v.clienteId)||'Balcão'),v.itens.length,`<span class="money" data-money="1">${fmt(v.total)}</span>`,esc(v.pagamento)]))}`)}
function openQuickSale(){const opts=DB.produtos.map(p=>`<option value="${p.id}">${esc(p.nome)} (${esc(p.unidade||'kg')})</option>`).join(''); modal('Venda rápida',`<div class="form-row two"><div><label class="label">Cliente</label><select id="saleCli"><option value="">Balcão</option>${DB.clientes.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join('')}</select></div><div><label class="label">Pagamento</label><select id="salePay"><option>PIX</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Boleto/Fiado</option></select></div></div><div id="saleItems"></div><button class="btn" onclick="App.addSaleItem()">+ Item</button>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.saveSale()">Salvar venda</button>`); addSaleItem();}
function addSaleItem(){const el=document.getElementById('saleItems'); el.insertAdjacentHTML('beforeend',`<div class="form-row three sale-row"><div><label class="label">Produto</label><select class="sProd">${DB.produtos.map(p=>`<option value="${p.id}">${esc(p.nome)}</option>`).join('')}</select></div><div><label class="label">Qtd/Peso</label><input class="sQtd" inputmode="decimal" value="1"></div><div><label class="label">Valor unitário</label><input class="sVlr" inputmode="decimal" placeholder="sem valor falso"></div></div>`)}
function saveSale(){const rows=[...document.querySelectorAll('.sale-row')]; const itens=rows.map(r=>({produtoId:r.querySelector('.sProd').value,qtd:num(r.querySelector('.sQtd').value),unit:num(r.querySelector('.sVlr').value)})).filter(i=>i.produtoId&&i.qtd>0); const total=itens.reduce((a,i)=>a+i.qtd*i.unit,0); const venda={id:uid('ven'),data:today(),clienteId:val('saleCli'),pagamento:val('salePay'),itens,total,status:'finalizada'}; DB.vendas.unshift(venda); if(venda.pagamento==='Boleto/Fiado')DB.financeiro.unshift({id:uid('fin'),tipo:'receber',origem:'venda',refId:venda.id,descricao:'Venda/fiado',valor:total,vencimento:today(),status:'aberto'}); audit('criar','venda',venda.id,null,venda); save(); closeModal(true); toast('Venda salva'); render()}
function pedidos(){set(`<div class="toolbar"><button class="primary" onclick="App.editPedido()">Nova encomenda</button></div>${table(['Data','Cliente','Retirada','Status','Total','Ações'],DB.pedidos.map(p=>[dateBR(p.data),esc(findName(DB.clientes,p.clienteId)||p.cliente||''),dateBR(p.retirada),statusSel(p.id,p.status),`<span class="money" data-money="1">${fmt(p.total)}</span>`,`<button onclick="App.editPedido('${p.id}')">Abrir</button>`]))}`)}
function statusSel(id,s){return `<select onchange="App.statusPedido('${id}',this.value)">${['novo','separando','pronto','entregue','cancelado'].map(x=>`<option ${x===s?'selected':''}>${x}</option>`).join('')}</select>`}
function statusPedido(id,s){const p=DB.pedidos.find(x=>x.id===id); if(!p)return; const before={...p}; p.status=s; if(s==='pronto')notify('alerta','Pedido pronto','Pedido/encomenda pronto para avisar o cliente','jarvis',{tipo:'pedido',id}); audit('status','pedido',id,before,p); save(); toast('Status atualizado'); render()}
function editPedido(id){const p=id?DB.pedidos.find(x=>x.id===id):{id:'',data:today(),retirada:today(),status:'novo',itens:[],total:0}; modal(id?'Editar encomenda':'Nova encomenda',`<div class="form-row three"><div><label class="label">Cliente</label><select id="pedCli"><option value="">Balcão</option>${DB.clientes.map(c=>`<option value="${c.id}" ${c.id===p.clienteId?'selected':''}>${esc(c.nome)}</option>`).join('')}</select></div><div><label class="label">Retirada/entrega</label><input id="pedRet" type="date" value="${p.retirada||today()}"></div><div><label class="label">Status</label><select id="pedStatus">${['novo','separando','pronto','entregue','cancelado'].map(s=>`<option ${s===p.status?'selected':''}>${s}</option>`).join('')}</select></div></div><label class="label">Observações</label><textarea id="pedObs">${esc(p.obs||'')}</textarea>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.savePedido('${id||''}')">Salvar</button>`)}
function savePedido(id){let p=id?DB.pedidos.find(x=>x.id===id):null; const before=p?{...p}:null; if(!p){p={id:uid('ped'),data:today(),itens:[],total:0}; DB.pedidos.unshift(p)} Object.assign(p,{clienteId:val('pedCli'),retirada:val('pedRet'),status:val('pedStatus'),obs:val('pedObs')}); if(p.status==='pronto')notify('alerta','Encomenda pronta','Enviar aviso ao cliente','jarvis',{tipo:'pedido',id:p.id}); audit(id?'editar':'criar','pedido',p.id,before,p); save(); closeModal(true); render()}
function estoque(){set(`<div class="toolbar"><button class="primary" onclick="App.editProduto()">Novo produto</button><button onclick="App.editLote()">Novo lote</button></div><h3>Produtos</h3>${table(['Código','Nome','Categoria','Unid.','Venda','Ações'],DB.produtos.map(p=>[esc(p.codigo||''),esc(p.nome),esc(p.categoria||''),esc(p.unidade||'kg'),`<span class="money" data-money="1">${p.preco?fmt(p.preco):'—'}</span>`,`<button onclick="App.editProduto('${p.id}')">Editar</button>`]))}<h3 style="margin-top:20px">Lotes e validade</h3>${table(['Produto','Lote','Qtd','Validade','Local','Destino/Status','Ações'],DB.lotes.map(l=>[esc(prodName(l.produtoId)),esc(l.lote),`${l.qtd} ${esc(l.unidade||'kg')}`,dateBR(l.validade),esc(l.local||''),esc(l.status||'estoque'),`<button onclick="App.editLote('${l.id}')">Editar</button>`]))}`)}
function editProduto(id){const p=id?DB.produtos.find(x=>x.id===id):{}; modal(id?'Editar produto':'Novo produto',`<div class="form-row three"><div><label class="label">Código interno</label><input id="pCod" value="${esc(p.codigo||'')}"></div><div><label class="label">Nome</label><input id="pNome" value="${esc(p.nome||'')}"></div><div><label class="label">Categoria</label><select id="pCat">${['Bovino','Suíno','Frango','Linguiça/embutido','Temperado','Carvão/mercearia','Outro'].map(c=>`<option ${c===p.categoria?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="form-row three"><div><label class="label">Unidade</label><select id="pUn"><option ${p.unidade==='kg'?'selected':''}>kg</option><option ${p.unidade==='un'?'selected':''}>un</option><option ${p.unidade==='pct'?'selected':''}>pct</option></select></div><div><label class="label">Preço venda</label><input id="pPreco" inputmode="decimal" value="${p.preco||''}" placeholder="preencha o valor real"></div><div><label class="label">Código de barras</label><input id="pBar" value="${esc(p.barras||'')}"></div></div>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.saveProduto('${id||''}')">Salvar</button>`)}
function saveProduto(id){let p=id?DB.produtos.find(x=>x.id===id):null; const before=p?{...p}:null; if(!p){p={id:uid('pro')}; DB.produtos.unshift(p)} Object.assign(p,{codigo:val('pCod'),nome:val('pNome'),categoria:val('pCat'),unidade:val('pUn'),preco:num(val('pPreco')),barras:val('pBar')}); audit(id?'editar':'criar','produto',p.id,before,p); save(); closeModal(true); render()}
function editLote(id){const l=id?DB.lotes.find(x=>x.id===id):{}; modal(id?'Editar lote':'Novo lote',`<div class="form-row three"><div><label class="label">Produto</label><select id="lProd">${DB.produtos.map(p=>`<option value="${p.id}" ${p.id===l.produtoId?'selected':''}>${esc(p.nome)}</option>`).join('')}</select></div><div><label class="label">Lote</label><input id="lLote" value="${esc(l.lote||'')}"></div><div><label class="label">Validade</label><input id="lVal" type="date" value="${l.validade||''}"></div></div><div class="form-row three"><div><label class="label">Quantidade</label><input id="lQtd" inputmode="decimal" value="${l.qtd||''}"></div><div><label class="label">Local</label><input id="lLocal" placeholder="Câmara fria, freezer, balcão" value="${esc(l.local||'')}"></div><div><label class="label">Status</label><select id="lStatus">${['estoque','reservado','produção','vendido','perda','devolução'].map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select></div></div>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.saveLote('${id||''}')">Salvar</button>`)}
function saveLote(id){let l=id?DB.lotes.find(x=>x.id===id):null; const before=l?{...l}:null; if(!l){l={id:uid('lot')}; DB.lotes.unshift(l)} const p=DB.produtos.find(x=>x.id===val('lProd')); Object.assign(l,{produtoId:val('lProd'),lote:val('lLote'),validade:val('lVal'),qtd:num(val('lQtd')),unidade:p?.unidade||'kg',local:val('lLocal'),status:val('lStatus')}); audit(id?'editar':'criar','lote',l.id,before,l); save(); closeModal(true); render()}
function compras(){set(`<div class="toolbar"><button class="primary" onclick="document.getElementById('xmlIn').click()">Importar XML NF-e</button><button onclick="App.compraManual()">Entrada manual sem NF</button><input id="xmlIn" type="file" accept=".xml,text/xml" hidden onchange="App.importXml(event)"></div>${table(['NF','Fornecedor','Data','Itens','Total','Boletos','Ações'],DB.compras.map(c=>[`${esc(c.numero||'')} / ${esc(c.serie||'')}`,esc(c.emitente?.nome||''),dateBR(c.emissao),c.itens?.length||0,`<span class="money" data-money="1">${fmt(c.total)}</span>`,c.duplicatas?.length||0,`<button onclick="App.viewCompra('${c.id}')">Abrir</button>`]))}`)}
function parseXml(txt){const xml=new DOMParser().parseFromString(txt,'text/xml'); const q=(sel,ctx=xml)=>ctx.querySelector(sel)?.textContent?.trim()||''; const qa=(sel,ctx=xml)=>[...ctx.querySelectorAll(sel)]; const inf=xml.querySelector('infNFe'); const emit=xml.querySelector('emit'); const total=xml.querySelector('ICMSTot'); const compra={id:uid('nfe'),chave:(inf?.getAttribute('Id')||'').replace(/^NFe/,''),numero:q('ide nNF'),serie:q('ide serie'),natureza:q('ide natOp'),emissao:q('ide dhEmi').slice(0,10),total:nXml(q('ICMSTot vNF')),totais:{prod:nXml(q('ICMSTot vProd')),desc:nXml(q('ICMSTot vDesc')),frete:nXml(q('ICMSTot vFrete')),ipi:nXml(q('ICMSTot vIPI')),pis:nXml(q('ICMSTot vPIS')),cofins:nXml(q('ICMSTot vCOFINS')),icms:nXml(q('ICMSTot vICMS')),st:nXml(q('ICMSTot vST')),outro:nXml(q('ICMSTot vOutro'))},emitente:{cnpj:q('emit CNPJ'),nome:q('emit xNome'),fantasia:q('emit xFant'),ie:q('emit IE'),cep:q('emit CEP'),logradouro:q('emit xLgr'),numero:q('emit nro'),bairro:q('emit xBairro'),cidade:q('emit xMun'),uf:q('emit UF'),fone:q('emit fone')},itens:[],duplicatas:qa('cobr dup').map(d=>({numero:q('nDup',d),vencimento:q('dVenc',d),valor:nXml(q('vDup',d)),status:'aberto'})),rawResumo:''}; compra.itens=qa('det').map(d=>{const xp=q('prod xProd',d); const split=splitProd(xp); return {nItem:d.getAttribute('nItem'),cProd:q('prod cProd',d),codigoComercial:split.codigo,descricao:split.descricao,marca:split.marca,cEAN:q('prod cEAN',d),ncm:q('prod NCM',d),cest:q('prod CEST',d),cfop:q('prod CFOP',d),uCom:q('prod uCom',d),qCom:nXml(q('prod qCom',d)),vUnCom:nXml(q('prod vUnCom',d)),vProd:nXml(q('prod vProd',d)),vDesc:nXml(q('prod vDesc',d)),orig:q('ICMS orig',d),cst:q('ICMS CST',d),icms:nXml(q('ICMS vICMS',d)||q('ICMS vICMSSTRet',d)),ipi:nXml(q('IPI vIPI',d)),pis:nXml(q('PIS vPIS',d)),cofins:nXml(q('COFINS vCOFINS',d)),destino:'estoque',osId:'',placa:'',obs:q('infAdProd',d),xProdOriginal:xp}}); return compra}
function nXml(v){if(v==null||v==='')return 0; return Number(String(v).replace(',','.'))||0}
function splitProd(x){let s=String(x||'').trim(); let marca=''; const m=s.match(/\s+-\s+([A-Z0-9ÁÉÍÓÚÂÊÔÃÕÇ .]{2,})$/i); if(m){marca=m[1].trim(); s=s.slice(0,m.index).trim()} let codigo=''; let desc=s; const p=s.match(/^([A-Z0-9]{2,}[A-Z0-9.\/\-]*)\s*[- ]\s*(.+)$/i); if(p){codigo=p[1].trim(); desc=p[2].trim()} return {codigo,descricao:desc,marca}}
function importXml(ev){const file=ev.target.files[0]; if(!file)return; file.text().then(txt=>{const c=parseXml(txt); DB.compras.unshift(c); const f=DB.fornecedores.find(x=>x.cnpj===c.emitente.cnpj); if(!f)DB.fornecedores.unshift({id:uid('for'),nome:c.emitente.nome,fantasia:c.emitente.fantasia,cnpj:c.emitente.cnpj,ie:c.emitente.ie,cep:c.emitente.cep,logradouro:c.emitente.logradouro,numero:c.emitente.numero,bairro:c.emitente.bairro,cidade:c.emitente.cidade,uf:c.emitente.uf,fone:c.emitente.fone}); c.duplicatas.forEach(d=>DB.financeiro.unshift({id:uid('fin'),tipo:'pagar',origem:'nfe',refId:c.id,descricao:`NF ${c.numero} - ${c.emitente.nome} - dup ${d.numero}`,valor:d.valor,vencimento:d.vencimento,status:'aberto',fornecedor:c.emitente.nome})); audit('importar','nfe',c.id,null,c); save(); toast('NF-e importada com espelho fiscal e boletos'); viewCompra(c.id); ev.target.value=''})}
function viewCompra(id){const c=DB.compras.find(x=>x.id===id); if(!c)return; const body=`<div class="grid cols-3"><div class="card"><b>NF</b><p>${esc(c.numero)} série ${esc(c.serie)}</p><p>${dateBR(c.emissao)}</p><p>Chave: ${esc(c.chave)}</p></div><div class="card"><b>Fornecedor</b><p>${esc(c.emitente.nome)}</p><p>${esc(c.emitente.cnpj)} IE ${esc(c.emitente.ie)}</p></div><div class="card"><b>Total</b><p class="money">${fmt(c.total)}</p><p>${c.duplicatas.length} boleto(s)</p></div></div><h3>Itens</h3>${table(['Item','Cód. forn.','Cód./OEM','Descrição','Marca','EAN','NCM','CEST','CFOP','Qtd','Unit','Total','Destino'],c.itens.map((it,i)=>[it.nItem,esc(it.cProd),esc(it.codigoComercial),esc(it.descricao),esc(it.marca),esc(it.cEAN),esc(it.ncm),esc(it.cest),esc(it.cfop),it.qCom,fmt(it.vUnCom),fmt(it.vProd-it.vDesc),destinoSelect(id,i,it)]))}<h3>Boletos / duplicatas</h3>${table(['Nº','Vencimento','Valor','Status'],c.duplicatas.map(d=>[esc(d.numero),dateBR(d.vencimento),fmt(d.valor),esc(d.status)]))}`; modal('Espelho da NF-e',body,`<button onclick="App.closeModal(true)">Fechar</button><button class="primary" onclick="App.saveVinculosCompra('${id}')">Salvar vínculos</button>`)}
function destinoSelect(cid,i,it){return `<select class="dest" data-i="${i}"><option ${it.destino==='estoque'?'selected':''}>estoque</option><option ${it.destino==='os'?'selected':''}>os</option><option ${it.destino==='placa'?'selected':''}>placa</option><option ${it.destino==='garantia'?'selected':''}>garantia</option><option ${it.destino==='devolução'?'selected':''}>devolução</option><option ${it.destino==='uso interno'?'selected':''}>uso interno</option><option ${it.destino==='outro'?'selected':''}>outro</option></select><input class="oslink" data-i="${i}" placeholder="placa/O.S./obs" value="${esc(it.placa||it.osId||it.obsDestino||'')}">`}
function saveVinculosCompra(id){const c=DB.compras.find(x=>x.id===id); document.querySelectorAll('.dest').forEach(sel=>{const i=Number(sel.dataset.i); c.itens[i].destino=sel.value; c.itens[i].obsDestino=document.querySelector(`.oslink[data-i="${i}"]`)?.value||''}); audit('vincular','nfe',id,null,c,'destino de itens'); save(); toast('Vínculos salvos')}
function compraManual(){modal('Entrada manual sem nota',`<div class="form-row three"><div><label class="label">Fornecedor</label><input id="cmFor"></div><div><label class="label">Descrição</label><input id="cmDesc"></div><div><label class="label">Valor total</label><input id="cmValor" inputmode="decimal"></div></div><div class="form-row three"><div><label class="label">Parcelas/boletos</label><input id="cmParc" type="number" min="1" value="1"></div><div><label class="label">1º vencimento</label><input id="cmVenc" type="date" value="${today()}"></div><div><label class="label">Destino</label><select id="cmDest"><option>estoque</option><option>os</option><option>uso interno</option></select></div></div>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.saveCompraManual()">Salvar entrada</button>`)}
function saveCompraManual(){const total=num(val('cmValor')); const parc=Math.max(1,parseInt(val('cmParc')||'1',10)); const c={id:uid('man'),manual:true,numero:'MANUAL-'+Date.now(),emissao:today(),emitente:{nome:val('cmFor')},itens:[{descricao:val('cmDesc'),vProd:total,destino:val('cmDest')}],total,duplicatas:[]}; for(let i=0;i<parc;i++){const venc=addMonths(val('cmVenc'),i); const valor=+(total/parc).toFixed(2); c.duplicatas.push({numero:String(i+1).padStart(3,'0'),vencimento:venc,valor,status:'aberto'}); DB.financeiro.unshift({id:uid('fin'),tipo:'pagar',origem:'entrada manual',refId:c.id,descricao:`Entrada manual ${c.emitente.nome}`,valor,vencimento:venc,status:'aberto'})} DB.compras.unshift(c); audit('criar','entrada_manual',c.id,null,c); save(); closeModal(true); render()}
function addMonths(iso,m){const [a,mo,d]=iso.split('-').map(Number); const dt=new Date(a,mo-1+m,d,12); return dt.toISOString().slice(0,10)}
function clientes(){crudPessoas('clientes')}
function fornecedores(){crudPessoas('fornecedores')}
function crudPessoas(tipo){const arr=DB[tipo]; set(`<div class="toolbar"><button class="primary" onclick="App.editPessoa('${tipo}')">Novo</button></div>${table(['Nome/Razão','CPF/CNPJ','Telefone','Cidade','Ações'],arr.map(p=>[esc(p.nome||p.razao||''),esc(p.cnpj||p.cpf||''),esc(p.fone||p.whatsapp||''),esc(p.cidade||''),`<button onclick="App.editPessoa('${tipo}','${p.id}')">Editar</button><button class="danger" onclick="App.delPessoa('${tipo}','${p.id}')">Excluir</button>`]))}`)}
function editPessoa(tipo,id){const p=id?DB[tipo].find(x=>x.id===id):{}; modal((id?'Editar ':'Novo ')+(tipo==='clientes'?'cliente':'fornecedor'),`<div class="form-row three"><div><label class="label">Nome/Razão</label><input id="peNome" value="${esc(p.nome||'')}"></div><div><label class="label">Fantasia</label><input id="peFant" value="${esc(p.fantasia||'')}"></div><div><label class="label">CPF/CNPJ</label><input id="peDoc" value="${esc(p.cnpj||p.cpf||'')}"></div></div><div class="form-row three"><div><label class="label">IE/RG</label><input id="peIE" value="${esc(p.ie||p.rg||'')}"></div><div><label class="label">Telefone</label><input id="peFone" value="${esc(p.fone||'')}"></div><div><label class="label">WhatsApp</label><input id="peWhats" value="${esc(p.whatsapp||'')}"></div></div><div class="form-row three"><div><label class="label">CEP</label><input id="peCep" value="${esc(p.cep||'')}"><button class="btn" onclick="App.cepFill('peCep','pe')">Buscar CEP</button></div><div><label class="label">Rua</label><input id="pelogradouro" value="${esc(p.logradouro||'')}"></div><div><label class="label">Número</label><input id="peNum" value="${esc(p.numero||'')}"></div></div><div class="form-row three"><div><label class="label">Bairro</label><input id="pebairro" value="${esc(p.bairro||'')}"></div><div><label class="label">Cidade</label><input id="pelocalidade" value="${esc(p.cidade||'')}"></div><div><label class="label">UF</label><input id="peuf" value="${esc(p.uf||'')}"></div></div><label class="label">Observações</label><textarea id="peObs">${esc(p.obs||'')}</textarea>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.savePessoa('${tipo}','${id||''}')">Salvar</button>`)}
function savePessoa(tipo,id){let p=id?DB[tipo].find(x=>x.id===id):null; const before=p?{...p}:null; if(!p){p={id:uid(tipo.slice(0,3))}; DB[tipo].unshift(p)} Object.assign(p,{nome:val('peNome'),fantasia:val('peFant'),cnpj:val('peDoc'),ie:val('peIE'),fone:val('peFone'),whatsapp:val('peWhats'),cep:val('peCep'),logradouro:val('pelogradouro'),numero:val('peNum'),bairro:val('pebairro'),cidade:val('pelocalidade'),uf:val('peuf'),obs:val('peObs')}); audit(id?'editar':'criar',tipo,p.id,before,p); save(); closeModal(true); render()}
function delPessoa(tipo,id){const motivo=prompt('Motivo obrigatório para excluir:'); if(!motivo)return; const i=DB[tipo].findIndex(x=>x.id===id); if(i<0)return; const before=DB[tipo][i]; DB[tipo].splice(i,1); audit('excluir',tipo,id,before,null,motivo); save(); render()}
function financeiro(){const rec=DB.financeiro.filter(f=>f.tipo==='receber').reduce((a,b)=>a+num(b.valor),0); const pag=DB.financeiro.filter(f=>f.tipo==='pagar').reduce((a,b)=>a+num(b.valor),0); set(`<div class="grid cols-3"><div class="card kpi"><span>Receitas</span><strong class="money">${fmt(rec)}</strong></div><div class="card kpi"><span>Despesas</span><strong class="money">${fmt(pag)}</strong></div><div class="card kpi"><span>Saldo previsto</span><strong class="money">${fmt(rec-pag)}</strong></div></div><div class="toolbar"><button class="primary" onclick="App.editFin()">Novo lançamento</button></div>${table(['Tipo','Origem','Descrição','Vencimento','Valor','Status','Ações'],DB.financeiro.map(f=>[esc(f.tipo),esc(f.origem||''),esc(f.descricao),dateBR(f.vencimento),`<span class="money">${fmt(f.valor)}</span>`,esc(f.status),`<button onclick="App.editFin('${f.id}')">Editar</button><button class="danger" onclick="App.delFin('${f.id}')">Excluir</button>`]))}`)}
function editFin(id){const f=id?DB.financeiro.find(x=>x.id===id):{}; modal(id?'Editar financeiro':'Novo lançamento',`<div class="form-row three"><div><label class="label">Tipo</label><select id="fiTipo"><option ${f.tipo==='receber'?'selected':''}>receber</option><option ${f.tipo==='pagar'?'selected':''}>pagar</option></select></div><div><label class="label">Vencimento</label><input id="fiVenc" type="date" value="${f.vencimento||today()}"></div><div><label class="label">Valor</label><input id="fiValor" inputmode="decimal" value="${f.valor||''}"></div></div><label class="label">Descrição</label><input id="fiDesc" value="${esc(f.descricao||'')}"><label class="label">Status</label><select id="fiStatus">${['aberto','pago','parcial','cancelado','vencido'].map(s=>`<option ${s===f.status?'selected':''}>${s}</option>`).join('')}</select>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.saveFin('${id||''}')">Salvar</button>`)}
function saveFin(id){let f=id?DB.financeiro.find(x=>x.id===id):null; const before=f?{...f}:null; if(!f){f={id:uid('fin')}; DB.financeiro.unshift(f)} Object.assign(f,{tipo:val('fiTipo'),vencimento:val('fiVenc'),valor:num(val('fiValor')),descricao:val('fiDesc'),status:val('fiStatus'),origem:f.origem||'manual'}); audit(id?'editar':'criar','financeiro',f.id,before,f); save(); closeModal(true); render()}
function delFin(id){const motivo=prompt('Motivo obrigatório para excluir lançamento financeiro:'); if(!motivo)return; const i=DB.financeiro.findIndex(x=>x.id===id); if(i<0)return; const before=DB.financeiro[i]; DB.financeiro.splice(i,1); audit('excluir','financeiro',id,before,null,motivo); save(); render()}
function producao(){set(`<div class="toolbar"><button class="primary" onclick="App.editProdProc()">Nova produção/desossa</button></div>${table(['Data','Origem','Resultado','Perdas','Responsável','Ações'],DB.producao.map(p=>[dateBR(p.data),esc(p.origem),esc(p.resultado),esc(p.perdas),esc(p.resp),`<button onclick="App.editProdProc('${p.id}')">Abrir</button>`]))}`)}
function editProdProc(id){const p=id?DB.producao.find(x=>x.id===id):{}; modal(id?'Editar produção':'Nova produção/desossa',`<div class="form-row two"><div><label class="label">Origem/lote</label><input id="prOrig" value="${esc(p.origem||'')}"></div><div><label class="label">Responsável</label><input id="prResp" value="${esc(p.resp||'')}"></div></div><label class="label">Resultado dos cortes</label><textarea id="prRes" placeholder="ex.: 12kg patinho, 8kg coxão mole...">${esc(p.resultado||'')}</textarea><label class="label">Perdas/aparas</label><textarea id="prPer">${esc(p.perdas||'')}</textarea>`, `<button onclick="App.closeModal(true)">Cancelar</button><button class="primary" onclick="App.saveProdProc('${id||''}')">Salvar</button>`)}
function saveProdProc(id){let p=id?DB.producao.find(x=>x.id===id):null; const before=p?{...p}:null; if(!p){p={id:uid('prd'),data:today()}; DB.producao.unshift(p)} Object.assign(p,{origem:val('prOrig'),resp:val('prResp'),resultado:val('prRes'),perdas:val('prPer')}); audit(id?'editar':'criar','producao',p.id,before,p); save(); closeModal(true); render()}
function notificacoes(){set(`${table(['Data','Tipo','Título','Mensagem','Status'],DB.notificacoes.map(n=>[dateBR(n.at),esc(n.tipo),esc(n.titulo),esc(n.msg),n.lida?'lida':'não lida']))}`)}
function ia(){set(`<div class="card"><h3>thIAguinho IA — Casa de Carnes</h3><p class="subtle">IA local de apoio: não inventa preços, não afirma estoque sem registro e oculta valores para equipe.</p><div id="aiMsgs" class="ai-box"></div><div class="form-row two"><input id="aiInput" placeholder="Pergunte sobre validade, estoque, pedidos, financeiro..."><button class="primary" onclick="App.askAI()">Enviar</button></div></div>`)}
function askAI(){const q=val('aiInput'); if(!q)return; const box=document.getElementById('aiMsgs'); box.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(q)}</div>`); const resp=aiResp(q); box.insertAdjacentHTML('beforeend',`<div class="msg bot">${resp}</div>`); document.getElementById('aiInput').value=''; box.scrollTop=box.scrollHeight}
function aiResp(q){const s=q.toLowerCase(); if(s.includes('valid')){const lots=DB.lotes.filter(l=>l.validade&&days(l.validade)<=5); return lots.length?`Lotes próximos do vencimento:<br>${lots.map(l=>`• ${esc(prodName(l.produtoId))}, lote ${esc(l.lote)}, validade ${dateBR(l.validade)}`).join('<br>')}`:'Não há lote com vencimento em até 5 dias registrado.'} if(s.includes('financeiro')||s.includes('lucro')||s.includes('valor')){if(noMoneyRole)return 'Seu perfil não tem permissão para consultar valores financeiros.'; const rec=DB.financeiro.filter(f=>f.tipo==='receber').reduce((a,b)=>a+num(b.valor),0), pag=DB.financeiro.filter(f=>f.tipo==='pagar').reduce((a,b)=>a+num(b.valor),0); return `Dados reais registrados: receitas ${fmt(rec)}, despesas ${fmt(pag)}, saldo previsto ${fmt(rec-pag)}.`} if(s.includes('pedido'))return `Existem ${DB.pedidos.filter(p=>!['entregue','cancelado'].includes(p.status)).length} pedidos abertos.`; return 'Eu só respondo com base nos dados registrados neste sistema. Pergunte por validade, pedidos, estoque ou financeiro conforme seu perfil.'}
function modulos(){set(`<div class="card"><h3>Módulos por unidade</h3><p class="subtle">Bloqueio por módulo preserva dependências operacionais. Desmarcar financeiro oculta DRE/valores; desmarcar NF não apaga notas já importadas.</p></div><div class="grid cols-2">${modules.filter(m=>m[0]!=='modulos').map(m=>`<div class="card module-card"><div><b>${m[1]}</b><p class="subtle">${m[0]}</p></div><input type="checkbox" ${DB.tenant.modulos?.[m[0]]===false?'':'checked'} onchange="App.setModulo('${m[0]}',this.checked)"></div>`).join('')}</div>`)}
function setModulo(id,on){DB.tenant.modulos=DB.tenant.modulos||{}; DB.tenant.modulos[id]=!!on; audit('modulo','tenant',id,null,{id,on}); save(); nav(); toast('Módulo atualizado')}
function auditoria(){set(table(['Data','Usuário','Ação','Entidade','Motivo'],DB.auditoria.map(a=>[dateBR(a.at),esc(a.usuario),esc(a.action),`${esc(a.entity)} ${esc(a.id)}`,esc(a.motivo||'')])))}
function table(headers,rows){return `<div class="table-wrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="subtle">Nenhum registro.</td></tr>`}</tbody></table></div>`}
function findName(arr,id){return arr.find(x=>x.id===id)?.nome}
function val(id){return document.getElementById(id)?.value||''}
function backup(){const blob=new Blob([JSON.stringify(DB,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='backup-caetano-'+today()+'.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(ev){const f=ev.target.files[0]; if(!f)return; f.text().then(t=>{DB=Object.assign(blank(),JSON.parse(t)); save(); toast('Backup restaurado'); render(); nav();})}
function seed(){if(DB.produtos.length)return; DB.produtos=[{id:uid('pro'),codigo:'',nome:'Produto sem preço cadastrado',categoria:'Bovino',unidade:'kg',preco:0}]; save()}
seed(); window.App={go,toggleMenu,toggleTheme,backup,restore,closeModal,openQuickSale,addSaleItem,saveSale,editPedido,savePedido,statusPedido,editProduto,saveProduto,editLote,saveLote,importXml,viewCompra,saveVinculosCompra,compraManual,saveCompraManual,editPessoa,savePessoa,delPessoa,cepFill,editFin,saveFin,delFin,editProdProc,saveProdProc,askAI,setModulo}; nav(); go(current);
})();
