(function(){
'use strict';
const APP='caetano_saas_pro_multiacougue_v3';
const DEMO_USERS={
 'superadmin@thiaguinho.com.br':{senha:'Caetano@177',role:'superadmin',nome:'Superadmin thIAguinho',tenantId:'global'},
 'admin@caetano.com.br':{senha:'Caetano@123',role:'admin',nome:'Admin Caetano',tenantId:'caetano'},
 'pdv@caetano.com.br':{senha:'Caixa@123',role:'pdv',nome:'Caixa Caetano',tenantId:'caetano'},
 'cozinha@caetano.com.br':{senha:'Cozinha@123',role:'cozinha',nome:'Cozinha Caetano',tenantId:'caetano'},
 'estoque@caetano.com.br':{senha:'Estoque@123',role:'estoque',nome:'Estoque Caetano',tenantId:'caetano'},
 'cliente@exemplo.com':{senha:'Cliente@123',role:'cliente',nome:'Cliente Teste',tenantId:'caetano',clienteId:'cliente_teste_001'}
};
function uid(){return Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9)}
function money(v){return (Number(v||0)).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function num(v){if(typeof v==='number')return v;let s=String(v??'').trim();if(!s)return 0;if(/^\d+\.\d+$/.test(s))return Number(s);s=s.replace(/\./g,'').replace(',','.');return Number(s)||0}
function isoToday(){return new Date().toISOString().slice(0,10)}
function brDate(iso){if(!iso)return'';let [a,m,d]=String(iso).slice(0,10).split('-');return d&&m&&a?`${d}/${m}/${a}`:String(iso)}
function safeId(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,60)||uid()}
function read(k,fb){try{return JSON.parse(localStorage.getItem(APP+'_'+k)||JSON.stringify(fb))}catch(e){return fb}}
function write(k,v){localStorage.setItem(APP+'_'+k,JSON.stringify(v));return v}
function getSession(){return read('session',null)}
function setSession(s){write('session',s)}
function logout(){localStorage.removeItem(APP+'_session');location.href='index.html'}
function toast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function voltarSeguro(dest='index.html'){if(history.length>1)history.back();else location.href=dest}
function injectBack(dest){if(location.pathname.endsWith('/index.html')||location.pathname==='/'||document.querySelector('.back-btn'))return;let b=document.createElement('button');b.className='btn back-btn';b.textContent='← Voltar';b.onclick=()=>voltarSeguro(dest||'index.html');document.body.prepend(b)}
function defaultModules(){return{pdv:true,estoque:true,comprasNFe:true,rotisseria:true,encomendas:true,financeiro:true,clientes:true,fornecedores:true,etiquetas:true,auditoria:true,relatorios:true,fidelidade:true}}
function defaultTenant(id,nome){return{id,nome,nicho:'acougue_rotisseria',status:'ativo',plano:'pro',tema:'dark',modulos:defaultModules(),cloudinary:{cloudName:'',uploadPreset:'',folderProdutos:id+'/produtos',folderComprovantes:id+'/comprovantes'},config:{controlarLote:true,controlarValidade:true,permitirVendaSemEstoque:false,timezone:'America/Sao_Paulo',moeda:'BRL'},categorias:['Bovinos','Suínos','Aves','Linguiças','Temperados','Rotisseria','Congelados','Mercearia'],formasPagamento:['Dinheiro','PIX','Débito','Crédito','Boleto','Transferência'],sequencias:{produto:1,venda:1,pedido:1,nfe:1,etiqueta:1},perfisPermitidos:['admin','pdv','cozinha','estoque','cliente'],criadoEm:new Date().toISOString()}}
function bootstrap(){let tenants=read('tenants',{});if(!tenants.caetano)tenants.caetano=defaultTenant('caetano','Caetano Carnes e Rotisseria');write('tenants',tenants);let usuarios=read('usuarios',{});Object.entries(DEMO_USERS).forEach(([email,u])=>{let id='demo_'+safeId(email);if(!usuarios[id])usuarios[id]={id,email,nome:u.nome,role:u.role,tenantId:u.tenantId,clienteId:u.clienteId||'',ativo:true}});write('usuarios',usuarios);let clientes=read('clientes_caetano',{});if(!clientes.cliente_teste_001)clientes.cliente_teste_001={id:'cliente_teste_001',tenantId:'caetano',nome:'Cliente Teste',email:'cliente@exemplo.com',telefone:'',ativo:true};write('clientes_caetano',clientes);}
function audit(tenantId,acao,entidade,id,antes,depois,motivo){let arr=read('auditoria_'+tenantId,[]);arr.unshift({id:uid(),tenantId,acao,entidade,entidadeId:id||'',usuario:getSession()?.email||'sistema',perfil:getSession()?.role||'',motivo:motivo||'',antes:antes||null,depois:depois||null,em:new Date().toISOString()});write('auditoria_'+tenantId,arr.slice(0,1000))}
function login(email,senha,role){bootstrap();email=String(email||'').trim().toLowerCase();let u=DEMO_USERS[email];if(!u||u.senha!==senha)throw new Error('Usuário ou senha inválidos.');if(role&&u.role!==role)throw new Error('Este e-mail não pertence ao perfil selecionado.');let s={email,nome:u.nome,role:u.role,tenantId:u.tenantId,clienteId:u.clienteId||'',logadoEm:new Date().toISOString()};setSession(s);localStorage.setItem(APP+'_last_'+u.role,email);return s}
function requireRole(roles){bootstrap();let s=getSession();if(!s){location.href='index.html';return null}if(roles&&!roles.includes(s.role)){alert('Acesso não permitido para este perfil.');location.href='index.html';return null}return s}
function tenant(id){let t=read('tenants',{});return t[id]||null}
function saveTenant(t){let all=read('tenants',{});let old=all[t.id];all[t.id]=t;write('tenants',all);audit(t.id,'salvar_tenant','tenant',t.id,old,t,'');return t}
function criarTenantCompleto(dados){let id=safeId(dados.id||dados.nome);let t=defaultTenant(id,dados.nome||id);t.responsavel=dados.responsavel||'';t.emailAdmin=dados.emailAdmin||'';t.telefone=dados.telefone||'';t.cloudinary={...t.cloudinary,cloudName:dados.cloudName||'',uploadPreset:dados.uploadPreset||''};saveTenant(t);return t}
function criarUsuarioCompleto(tenantId,dados){let all=read('usuarios',{});let id='user_'+safeId(dados.email||uid());let old=all[id];all[id]={id,tenantId,email:dados.email||'',nome:dados.nome||'',role:dados.role||'pdv',ativo:true,telefone:dados.telefone||'',criadoEm:new Date().toISOString(),permissoes:dados.permissoes||{}};write('usuarios',all);audit(tenantId,'criar_usuario','usuario',id,old,all[id],'Cadastro de equipe/usuário');return all[id]}
function upsert(collection,tenantId,obj){let key=collection+'_'+tenantId;let all=read(key,{});let id=obj.id||uid();let old=all[id];all[id]={...obj,id,tenantId,atualizadoEm:new Date().toISOString()};write(key,all);audit(tenantId,old?'alterar_'+collection:'criar_'+collection,collection,id,old,all[id],obj.motivoAuditoria||'');return all[id]}
function list(collection,tenantId){return Object.values(read(collection+'_'+tenantId,{}))}
function remove(collection,tenantId,id,motivo){if(!motivo)throw new Error('Motivo obrigatório.');let key=collection+'_'+tenantId;let all=read(key,{});let old=all[id];delete all[id];write(key,all);audit(tenantId,'excluir_'+collection,collection,id,old,null,motivo)}
async function uploadCloudinary(file,tenantId,folder){let t=tenant(tenantId)||{};let c=t.cloudinary||window.CAETANO_CLOUDINARY_PADRAO||{};if(!c.cloudName||!c.uploadPreset)throw new Error('Cloudinary não configurado para este açougue.');let fd=new FormData();fd.append('file',file);fd.append('upload_preset',c.uploadPreset);fd.append('folder',folder||c.folderProdutos||tenantId+'/produtos');let r=await fetch(`https://api.cloudinary.com/v1_1/${c.cloudName}/auto/upload`,{method:'POST',body:fd});let j=await r.json();if(!j.secure_url)throw new Error(j.error?.message||'Falha no upload Cloudinary');return j.secure_url}
function parseNFe(xmlText){let doc=new DOMParser().parseFromString(xmlText,'text/xml');let q=(sel,base=doc)=>base.querySelector(sel)?.textContent?.trim()||'';let inf=doc.querySelector('infNFe');let chave=(inf?.getAttribute('Id')||'').replace(/^NFe/,'');let emit=doc.querySelector('emit');let end=doc.querySelector('enderEmit');let total=doc.querySelector('ICMSTot');let nfe={id:'nfe_'+(chave||uid()),chave,numero:q('ide > nNF'),serie:q('ide > serie'),modelo:q('ide > mod'),natOp:q('ide > natOp'),dhEmi:q('ide > dhEmi'),fornecedor:{cnpj:q('CNPJ',emit),razao:q('xNome',emit),fantasia:q('xFant',emit),ie:q('IE',emit),telefone:q('fone',end),cep:q('CEP',end),logradouro:q('xLgr',end),numero:q('nro',end),bairro:q('xBairro',end),cidade:q('xMun',end),uf:q('UF',end)},totais:{vProd:num(q('vProd',total)),vDesc:num(q('vDesc',total)),vFrete:num(q('vFrete',total)),vIPI:num(q('vIPI',total)),vPIS:num(q('vPIS',total)),vCOFINS:num(q('vCOFINS',total)),vNF:num(q('vNF',total))},itens:[],duplicatas:[]};doc.querySelectorAll('det').forEach(det=>{let p=det.querySelector('prod');let x=q('xProd',p);let split=splitProduto(x);let imp=det.querySelector('imposto');nfe.itens.push({nItem:det.getAttribute('nItem'),codigoFornecedor:q('cProd',p),codigoOEM:split.codigoOEM,descricao:split.descricao,marca:split.marca,ean:q('cEAN',p),ncm:q('NCM',p),cest:q('CEST',p),cfop:q('CFOP',p),unidade:q('uCom',p),quantidade:num(q('qCom',p)),valorUnitario:num(q('vUnCom',p)),desconto:num(q('vDesc',p)),valorProduto:num(q('vProd',p)),totalLiquido:num(det.querySelector('vItem')?.textContent||q('vProd',p))-num(q('vDesc',p)),origem:q('orig',imp),cst:q('CST',imp),icms:num(q('vICMS',imp)||q('vICMSSTRet',imp)),ipi:num(q('vIPI',imp)),pis:num(q('vPIS',imp)),cofins:num(q('vCOFINS',imp)),destino:'estoque',osId:'',placa:'',finalidadeObs:''})});doc.querySelectorAll('dup').forEach(d=>nfe.duplicatas.push({numero:q('nDup',d),vencimento:q('dVenc',d),valor:num(q('vDup',d)),status:'aberto'}));return nfe}
function splitProduto(xProd){let raw=String(xProd||'').trim();let codigoOEM='',marca='',descricao=raw;let parts=raw.split(' - ').map(s=>s.trim()).filter(Boolean);if(parts.length>=2){marca=parts[parts.length-1];descricao=parts.slice(0,-1).join(' - ')}let m=descricao.match(/^([A-Z0-9\.\/]{2,20})[-\s]+(.+)$/i);if(m){codigoOEM=m[1].trim();descricao=m[2].trim()}return{codigoOEM,descricao,marca}}
function criarNFeCompleta(tenantId,nfe){let saved=upsert('nfeEntrada',tenantId,{...nfe,criadaEm:new Date().toISOString()});upsert('fornecedores',tenantId,{id:'forn_'+safeId(nfe.fornecedor.cnpj||nfe.fornecedor.razao),...nfe.fornecedor});nfe.itens.forEach((it,i)=>{upsert('itensFiscais',tenantId,{...it,id:saved.id+'_item_'+(i+1),nfeId:saved.id,chave:nfe.chave,fornecedor:nfe.fornecedor.razao,dataEntrada:nfe.dhEmi?.slice(0,10)||isoToday()});if(it.destino==='estoque')upsert('estoque',tenantId,{id:'est_'+safeId(it.codigoFornecedor+'_'+saved.id+'_'+i),codigo:it.codigoFornecedor,codigoOEM:it.codigoOEM,descricao:it.descricao,marca:it.marca,ncm:it.ncm,cfop:it.cfop,cest:it.cest,quantidade:it.quantidade,custoUnitario:it.valorUnitario,lote:saved.numero,validade:it.validade||'',origemNfe:saved.id})});nfe.duplicatas.forEach((d,i)=>upsert('financeiro',tenantId,{id:saved.id+'_dup_'+(i+1),tipo:'despesa',categoria:'Compra NF-e',descricao:`NF ${nfe.numero} - Parcela ${d.numero}`,valor:d.valor,vencimento:d.vencimento,status:'aberto',fornecedor:nfe.fornecedor.razao,nfeId:saved.id}));return saved}
function produtoPadrao(tenantId,d){let produtos=list('produtos',tenantId);let t=tenant(tenantId);let seq=(t?.sequencias?.produto||1);let codigo=d.codigo||('P'+String(seq).padStart(5,'0'));if(t){t.sequencias.produto=seq+1;saveTenant(t)}return upsert('produtos',tenantId,{codigo,nome:d.nome||'',categoria:d.categoria||'',tipoVenda:d.tipoVenda||'kg',precoKg:num(d.precoKg),precoUn:num(d.precoUn),custo:num(d.custo),ean:d.ean||'',ncm:d.ncm||'',cfop:d.cfop||'',fotoUrl:d.fotoUrl||'',ativo:true})}
function gerarEtiqueta(prod){return`<div class="label-preview"><b>${prod.nome||'PRODUTO'}</b><br><span>${prod.tipoVenda==='kg'?'PREÇO/KG':'PREÇO/UN'}: ${money(prod.tipoVenda==='kg'?prod.precoKg:prod.precoUn)}</span><br><small>Cód.: ${prod.codigo||''} · Val.: ${prod.validade||'__/__/____'}</small><br><div class="barcode">|||| ${prod.codigo||prod.ean||''} ||||</div><br><small>Caetano Carnes e Rotisseria</small></div>`}
window.Caetano={APP,bootstrap,login,logout,requireRole,getSession,toast,money,num,uid,read,write,tenant,saveTenant,criarTenantCompleto,criarUsuarioCompleto,upsert,list,remove,audit,uploadCloudinary,parseNFe,criarNFeCompleta,produtoPadrao,gerarEtiqueta,brDate,isoToday,voltarSeguro,injectBack};document.addEventListener('DOMContentLoaded',()=>{bootstrap();injectBack();let t=localStorage.getItem('caetano_theme')||'dark';document.documentElement.setAttribute('data-theme',t)});
})();
