(function(){'use strict';
const APP='caetano_saas_v1';
const DEFAULT_TENANT='caetano';
const roles={superadmin:'Superadmin',admin:'Admin do Açougue',pdv:'PDV / Caixa',balcao:'Açougueiro / Balcão',cozinha:'Cozinha / Rotisseria',estoque:'Estoque / Compras',cliente:'Cliente'};
const modules={pdv:true,balcao:true,cozinha:true,estoque:true,comprasNFe:true,financeiro:true,clientes:true,fornecedores:true,etiquetas:true,producao:true,encomendas:true,auditoria:true,relatorios:true,fidelidade:true};
function now(){return new Date().toISOString()}function id(p='id'){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function get(k,d){try{return JSON.parse(localStorage.getItem(APP+'_'+k))??d}catch(e){return d}}function set(k,v){localStorage.setItem(APP+'_'+k,JSON.stringify(v));return v}
function list(k){return get(k,[])}function saveList(k,arr){return set(k,arr)}function br(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function n(v){if(typeof v==='number')return v;let s=String(v??'').trim();if(!s)return 0;if(/^\d+\.\d+$/.test(s))return Number(s);s=s.replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'');return Number(s)||0}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function seed(){if(get('seeded'))return;set('tenants',[{id:'caetano',nome:'Caetano Carnes e Rotisseria',status:'ativo',plano:'pro',modulos:modules,tema:'dark'}]);set('users',[{id:id('u'),nome:'Superadmin thIAguinho',email:'superadmin@thiaguinho.com.br',senha:'Caetano@177',role:'superadmin',tenantId:'global',ativo:true},{id:id('u'),nome:'Admin Caetano',email:'admin@caetano.com.br',senha:'Caetano@123',role:'admin',tenantId:'caetano',ativo:true},{id:id('u'),nome:'Caixa Caetano',email:'pdv@caetano.com.br',senha:'Caixa@123',role:'pdv',tenantId:'caetano',ativo:true},{id:id('u'),nome:'Cozinha Caetano',email:'cozinha@caetano.com.br',senha:'Cozinha@123',role:'cozinha',tenantId:'caetano',ativo:true},{id:id('u'),nome:'Estoque Caetano',email:'estoque@caetano.com.br',senha:'Estoque@123',role:'estoque',tenantId:'caetano',ativo:true},{id:id('u'),nome:'Cliente Teste',email:'cliente@exemplo.com',senha:'Cliente@123',role:'cliente',tenantId:'caetano',ativo:true,clienteId:'cliente_teste'}]);set('produtos',[{id:id('p'),tenantId:'caetano',codigo:'PICANHA_KG',ean:'',nome:'PICANHA BOVINA',categoria:'carnes',tipoVenda:'kg',precoVenda:0,custo:0,ncm:'',cfopPadrao:'',controlarLote:true,ativo:true},{id:id('p'),tenantId:'caetano',codigo:'FRANGO_ASSADO',nome:'FRANGO ASSADO',categoria:'rotisseria',tipoVenda:'un',precoVenda:0,custo:0,ativo:true}]);set('clientes',[{id:'cliente_teste',tenantId:'caetano',nome:'Cliente Teste',telefone:'',email:'cliente@exemplo.com',pontos:0}]);set('fornecedores',[]);set('vendas',[]);set('compras',[]);set('financeiro',[]);set('estoque',[]);set('pedidos',[]);set('auditoria',[]);set('seeded',true)}
function audit(acao,entidade,idEnt,antes,depois,motivo=''){let a=list('auditoria');a.unshift({id:id('aud'),tenantId:session()?.tenantId||'',usuario:session()?.email||'anon',role:session()?.role||'',acao,entidade,idEnt,antes,depois,motivo,em:now()});saveList('auditoria',a)}
function login(email,senha,roleHint){const u=list('users').find(x=>x.email===email&&x.senha===senha&&x.ativo!==false&&(roleHint?x.role===roleHint:true));if(!u)throw new Error('Usuário ou senha inválidos.');set('session',u);localStorage.setItem(APP+'_last_'+(roleHint||'login'),email);audit('login','usuarios',u.id,null,{email:u.email,role:u.role});return u}
function logout(){audit('logout','usuarios',session()?.id,null,null);localStorage.removeItem(APP+'_session');location.href='index.html'}function session(){return get('session',null)}function requireRole(allowed){const s=session();if(!s||!allowed.includes(s.role)){location.href='index.html';return null}return s}
function tenant(){const s=session();let t=list('tenants').find(x=>x.id===(s?.tenantId||DEFAULT_TENANT));return t||list('tenants')[0]}
function byTenant(k){const tid=tenant()?.id;return list(k).filter(x=>!x.tenantId||x.tenantId===tid)}
function upsert(k,obj){let arr=list(k);if(!obj.id)obj.id=id(k);obj.tenantId=obj.tenantId||tenant()?.id||DEFAULT_TENANT;const i=arr.findIndex(x=>x.id===obj.id);const antes=i>=0?arr[i]:null;if(i>=0)arr[i]={...arr[i],...obj,atualizadoEm:now()};else arr.unshift({...obj,criadoEm:now()});saveList(k,arr);audit(i>=0?'alterar':'criar',k,obj.id,antes,obj);return obj}
function del(k,idItem,motivo){if(!motivo)throw new Error('Motivo obrigatório para excluir.');let arr=list(k);const old=arr.find(x=>x.id===idItem);saveList(k,arr.filter(x=>x.id!==idItem));audit('excluir',k,idItem,old,null,motivo)}
async function viaCep(cep){cep=String(cep||'').replace(/\D/g,'');if(cep.length!==8)throw new Error('CEP inválido.');const r=await fetch('https://viacep.com.br/ws/'+cep+'/json/');const d=await r.json();if(d.erro)throw new Error('CEP não encontrado.');return d}
function parseNFe(xmlText){const doc=new DOMParser().parseFromString(xmlText,'text/xml');const q=(sel,ctx=doc)=>ctx.querySelector(sel)?.textContent?.trim()||'';const inf=doc.querySelector('infNFe');const chave=(inf?.getAttribute('Id')||'').replace(/^NFe/,'');const emit=doc.querySelector('emit');const dest=doc.querySelector('dest');const itens=[...doc.querySelectorAll('det')].map(det=>{const prod=det.querySelector('prod');const x=q('xProd',prod);let codigoComercial='',descricao=x,marca='';const parts=x.split(' - ').map(s=>s.trim()).filter(Boolean);if(parts.length>=2){marca=parts[parts.length-1];const first=parts.slice(0,-1).join(' - ');const m=first.match(/^([A-Z0-9.\/]+)[- ](.+)$/i);if(m){codigoComercial=m[1];descricao=m[2]}else descricao=first}return{nItem:det.getAttribute('nItem'),cProd:q('cProd',prod),codigoComercial,descricao,marca,cEAN:q('cEAN',prod),ncm:q('NCM',prod),cest:q('CEST',prod),cfop:q('CFOP',prod),uCom:q('uCom',prod),qCom:n(q('qCom',prod)),vUnCom:n(q('vUnCom',prod)),vProd:n(q('vProd',prod)),vDesc:n(q('vDesc',prod)),vLiq:n(q('vItem',det))||Math.max(0,n(q('vProd',prod))-n(q('vDesc',prod))),orig:q('orig',det),cst:q('CST',det),icmsST:n(q('vICMSSTRet',det)),ipi:n(q('vIPI',det)),pis:n(q('vPIS',det)),cofins:n(q('vCOFINS',det)),destino:'estoque',vinculo:null}});return{chave,numero:q('nNF'),serie:q('serie'),modelo:q('mod'),natureza:q('natOp'),dataEmissao:q('dhEmi'),protocolo:q('nProt'),status:q('xMotivo'),emitente:{cnpj:q('CNPJ',emit),nome:q('xNome',emit),fantasia:q('xFant',emit),ie:q('IE',emit),telefone:q('fone',emit),cep:q('CEP',emit),logradouro:q('xLgr',emit),numero:q('nro',emit),bairro:q('xBairro',emit),cidade:q('xMun',emit),uf:q('UF',emit)},destinatario:{cnpj:q('CNPJ',dest),nome:q('xNome',dest)},totais:{vProd:n(q('ICMSTot>vProd')),vDesc:n(q('ICMSTot>vDesc')),vFrete:n(q('ICMSTot>vFrete')),vIPI:n(q('ICMSTot>vIPI')),vPIS:n(q('ICMSTot>vPIS')),vCOFINS:n(q('ICMSTot>vCOFINS')),vOutro:n(q('ICMSTot>vOutro')),vNF:n(q('ICMSTot>vNF'))},duplicatas:[...doc.querySelectorAll('dup')].map(d=>({nDup:q('nDup',d),dVenc:q('dVenc',d),vDup:n(q('vDup',d))})),itens,infCpl:q('infCpl')}}
function addFinanceiroFromNFe(nfe){const dups=nfe.duplicatas.length?nfe.duplicatas:[{nDup:'001',dVenc:'',vDup:nfe.totais.vNF}];dups.forEach(d=>upsert('financeiro',{tipo:'despesa',origem:'nfe',fornecedor:nfe.emitente.nome,documento:nfe.numero,valor:d.vDup,vencimento:d.dVenc,status:'aberto',nfeChave:nfe.chave,descricao:'NF-e '+nfe.numero+' - '+nfe.emitente.nome}))}
window.Caetano={APP,roles,modules,now,id,get,set,list,saveList,br,n,esc,toast,seed,login,logout,session,requireRole,tenant,byTenant,upsert,del,audit,viaCep,parseNFe,addFinanceiroFromNFe};document.addEventListener('DOMContentLoaded',seed);
})();
